import json
import os
from pptx import Presentation
from app.generators.base import BaseGenerator
from app.llm import client, prompts

OUTPUT_DIR = "outputs"

class PresentationGenerator(BaseGenerator):
    async def generate(self, source: str, config: dict) -> dict:
        # First, get JSON slide spec from LLM
        system_prompt = prompts.BASE_SYSTEM
        user_prompt = prompts.build_user_prompt(
            source, config, prompts.FORMAT_INSTRUCTIONS["presentation"]
        )
        json_str = await client.call_llm(system_prompt, user_prompt)

        # Clean possible markdown code fences
        json_str = json_str.strip()
        if json_str.startswith("```json"):
            json_str = json_str[7:]
        if json_str.endswith("```"):
            json_str = json_str[:-3]
        json_str = json_str.strip()

        slide_spec = json.loads(json_str)

        # Build PPTX
        prs = Presentation()
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = slide_spec.get("title", "Presentation")
        title_slide.placeholders[1].text = f"Generated by Gen AI Content Transformer"

        for s in slide_spec.get("slides", []):
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = s.get("title", "Slide")
            tf = slide.placeholders[1].text_frame
            tf.clear()
            bullets = s.get("bullets", [])
            if bullets:
                tf.text = bullets[0]
                for b in bullets[1:]:
                    p = tf.add_paragraph()
                    p.text = b
            # Optionally store speaker_notes in notes slide (skipped for brevity)

        os.makedirs(OUTPUT_DIR, exist_ok=True)
        filename = f"presentation_{hash(source) % 100000}.pptx"
        path = os.path.join(OUTPUT_DIR, filename)
        prs.save(path)

        return {
            "json": json_str,
            "pptx_path": path
        }
